# Generated by Django 6.0.7 on 2026-07-26 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(choices=[('girl', 'نورة'), ('boy', 'راشد')], default='girl', max_length=20, verbose_name='الشخصية')),
                ('character_name', models.CharField(default='نورة', max_length=100, verbose_name='اسم الشخصية')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='النقاط')),
                ('geckos_caught', models.PositiveIntegerField(default=0, verbose_name='عدد الوزغ')),
                ('time_remaining', models.PositiveIntegerField(default=0, verbose_name='الوقت المتبقي')),
                ('status', models.CharField(choices=[('win', 'فوز'), ('lose', 'خسارة')], default='lose', max_length=10, verbose_name='حالة اللعبة')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='المستوى')),
                ('lives', models.PositiveIntegerField(default=0, verbose_name='القلوب المتبقية')),
                ('stars', models.PositiveIntegerField(default=1, verbose_name='عدد النجوم')),
                ('completion', models.PositiveIntegerField(default=0, verbose_name='نسبة الإنجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ اللعب')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نتيجة لعبة',
                'verbose_name_plural': 'نتائج اللعبة',
                'ordering': ['-score', '-created_at'],
            },
        ),
    ]
