# Generated by Django 6.0.7 on 2026-07-26 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameresult',
            options={'ordering': ['-score', '-created_at'], 'verbose_name': 'نتيجة لعبة', 'verbose_name_plural': 'نتائج اللعبة'},
        ),
        migrations.AddField(
            model_name='gameresult',
            name='player_name',
            field=models.CharField(default='لاعب زائر', max_length=100, verbose_name='اسم اللاعب'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='submission_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='معرّف المحاولة'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='character',
            field=models.CharField(choices=[('girl', 'نورة'), ('boy', 'راشد')], default='girl', max_length=20, verbose_name='الشخصية'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='character_name',
            field=models.CharField(default='نورة', max_length=100, verbose_name='اسم الشخصية'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='completion',
            field=models.PositiveIntegerField(default=0, verbose_name='نسبة الإنجاز'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ اللعب'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='geckos_caught',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الوزغ'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='المستوى'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='lives',
            field=models.PositiveIntegerField(default=0, verbose_name='القلوب المتبقية'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='النقاط'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='stars',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد النجوم'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='status',
            field=models.CharField(choices=[('win', 'فوز'), ('lose', 'خسارة')], default='lose', max_length=10, verbose_name='حالة اللعبة'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='time_remaining',
            field=models.PositiveIntegerField(default=0, verbose_name='الوقت المتبقي'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]


