# Generated by Django 6.0.7 on 2026-07-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gameresult_options_gameresult_player_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='character',
            field=models.CharField(choices=[('girl', 'صالحة'), ('boy', 'مفرح')], default='girl', max_length=20, verbose_name='الشخصية'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='character_name',
            field=models.CharField(default='صالحة', max_length=100, verbose_name='اسم الشخصية'),
        ),
    ]

